# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# uv support as per https://github.com/readthedocs/readthedocs.org/issues/11289#issuecomment-2575933870
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv
    install:
      - uv pip install -r docs/requirements.txt
    build:
      html: |
        uv run sphinx-build \
          --show-traceback \
          --builder html \
          --doctree-dir _build/doctrees \
          --define language=en \
          docs/source \
          $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py
